#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 20, 2024 10:41:18 AM BST  platform: Windows NT

import sys


import sys
import serial
import time
import random
import threading

port = '/dev/ttyACM0'
baud_rate = 115200



def send_data(port, baud_rate, data): 
            print('trying to send data')
            # Open serial port
            ser = serial.Serial(
                port, 
                baud_rate, 
                timeout=1,
                parity=serial.PARITY_NONE,
                stopbits=serial.STOPBITS_ONE,
                bytesize=serial.EIGHTBITS
                )
            print(f"Opened port {port} with baud rate {baud_rate}")

            # Send data
            ser.write(data.encode())
            print(f"Sent data: {data}")
        
        # except serial.SerialException as e:
        #     print(f"Error opening or using the serial port: {e}")


if __name__ == '__main__':
    send_data(port, baud_rate, 'hello\n')