#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 20, 2024 10:42:01 AM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import support_FreeBot_support

import threading

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 



class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x204+361+111")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.stop_flag=False
        self.move_flag=False

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.517, rely=0.083, height=166, width=277)
        self.Button1_1.configure(activebackground="#ff0000")
        self.Button1_1.configure(activeforeground="black")
        self.Button1_1.configure(background="#ff0000")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 36 -weight bold")
        self.Button1_1.configure(foreground="#ffffff")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="#000000")
        self.Button1_1.configure(text='''STOP''')
        # self.Button1_1.configure(command=lambda: self.stop_callback)

        self.Button1_1.bind("<ButtonPress>",self.stop_pressed)
        self.Button1_1.bind("<ButtonRelease>", self.stop_released)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.017, rely=0.098, height=166, width=277)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#00d200")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 36 -weight bold")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''MOVE''')
        # self.Button1.configure(command=lambda: self.move_callback)

        self.Button1.bind("<ButtonPress>", self.move_pressed)
        self.Button1.bind("<ButtonRelease>", self.move_released)

    def stop_callback(self):
        #  support_func1=support_FreeBot_support.Robot()
        #  support_func1._callback_stop()
        print('stop')

    def move_callback(self):
        #  support_func2=support_FreeBot_support.Robot()
        #  support_func2._callback_move()
        self.Button1.configure(background="#ff0000")
        print('move')

    def stop_pressed(self,event):
        self.stop_flag=True
        self.move_flag=False
        print('Pressed Stop')

    def stop_released(self,event):
        self.stop_flag=False
        self.move_flag=False

    def move_pressed(self,event):
        self.stop_flag=False
        self.move_flag=True
        print('Pressed Move')

    def move_released(self,event):
        self.stop_flag=False
        self.move_flag=False

# def start_up():
#         support_FreeBot_support.main()

if __name__ == '__main__':
    support_FreeBot_support.main()






